/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface DiamondPackage {
  'id' : bigint,
  'diamondAmount' : bigint,
  'name' : string,
  'gameId' : bigint,
  'price' : bigint,
}
export interface Game { 'id' : bigint, 'name' : string, 'description' : string }
export interface LeaderboardEntry {
  'user' : Principal,
  'totalDiamonds' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'playerId' : string,
  'user' : Principal,
  'gameId' : bigint,
  'timestamp' : Time,
  'packageId' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPackage' : ActorMethod<[bigint, string, bigint, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'creditWallet' : ActorMethod<[Principal, bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGames' : ActorMethod<[], Array<Game>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getPackages' : ActorMethod<[bigint], Array<DiamondPackage>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, bigint, bigint], bigint>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];