/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'bank' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'playerId' : IDL.Text,
  'user' : IDL.Principal,
  'gameId' : IDL.Nat,
  'timestamp' : Time,
  'packageId' : IDL.Nat,
});
export const RedeemCode = IDL.Record({
  'redeemedBy' : IDL.Opt(IDL.Principal),
  'code' : IDL.Text,
  'redeemed' : IDL.Bool,
  'createdAt' : Time,
  'amount' : IDL.Nat,
});
export const TopUpRequestStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const TopUpRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : TopUpRequestStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'amount' : IDL.Nat,
  'utrRef' : IDL.Text,
});
export const Banner = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'ctaLink' : IDL.Text,
  'imageUrl' : IDL.Text,
  'ctaText' : IDL.Text,
  'subtitle' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Game = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'currency' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'user' : IDL.Principal,
  'totalDiamonds' : IDL.Nat,
});
export const DiamondPackage = IDL.Record({
  'id' : IDL.Nat,
  'diamondAmount' : IDL.Nat,
  'name' : IDL.Text,
  'gameId' : IDL.Nat,
  'price' : IDL.Nat,
});
export const PaymentConfig = IDL.Record({
  'ifscCode' : IDL.Opt(IDL.Text),
  'bankName' : IDL.Opt(IDL.Text),
  'upiId' : IDL.Opt(IDL.Text),
  'accountNumber' : IDL.Opt(IDL.Text),
  'accountHolder' : IDL.Opt(IDL.Text),
});
export const SiteConfig = IDL.Record({
  'backgroundColor' : IDL.Text,
  'tagline' : IDL.Text,
  'primaryColor' : IDL.Text,
  'banners' : IDL.Vec(Banner),
  'discountPercent' : IDL.Nat,
  'siteName' : IDL.Text,
  'promoText' : IDL.Text,
  'logoUrl' : IDL.Text,
  'featuredSectionHeading' : IDL.Text,
  'footerText' : IDL.Text,
});
export const UserStats = IDL.Record({
  'totalOrders' : IDL.Nat,
  'usersThisMonth' : IDL.Nat,
  'activeCustomers' : IDL.Nat,
  'pendingOrders' : IDL.Nat,
  'pendingTopUps' : IDL.Nat,
  'completedOrders' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBanner' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'addGame' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addPackage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'approveTopUpRequest' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createTopUpRequest' : IDL.Func(
      [IDL.Nat, PaymentMethod, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'creditWallet' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'generateRedeemCode' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllRedeemCodes' : IDL.Func([], [IDL.Vec(RedeemCode)], ['query']),
  'getAllTopUpRequests' : IDL.Func([], [IDL.Vec(TopUpRequest)], ['query']),
  'getBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
  'getMyTopUpRequests' : IDL.Func([], [IDL.Vec(TopUpRequest)], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getPackages' : IDL.Func([IDL.Nat], [IDL.Vec(DiamondPackage)], ['query']),
  'getPaymentConfig' : IDL.Func([], [IDL.Opt(PaymentConfig)], ['query']),
  'getSiteConfig' : IDL.Func([], [IDL.Opt(SiteConfig)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserStats' : IDL.Func([], [UserStats], ['query']),
  'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Nat], []),
  'redeemCode' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'rejectTopUpRequest' : IDL.Func([IDL.Nat], [], []),
  'removeBanner' : IDL.Func([IDL.Nat], [], []),
  'removeGame' : IDL.Func([IDL.Nat], [], []),
  'removePackage' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setPaymentConfig' : IDL.Func([PaymentConfig], [], []),
  'setSiteConfig' : IDL.Func([SiteConfig], [], []),
  'updateBanner' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateGame' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updatePackage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'upi' : IDL.Null, 'bank' : IDL.Null });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'playerId' : IDL.Text,
    'user' : IDL.Principal,
    'gameId' : IDL.Nat,
    'timestamp' : Time,
    'packageId' : IDL.Nat,
  });
  const RedeemCode = IDL.Record({
    'redeemedBy' : IDL.Opt(IDL.Principal),
    'code' : IDL.Text,
    'redeemed' : IDL.Bool,
    'createdAt' : Time,
    'amount' : IDL.Nat,
  });
  const TopUpRequestStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const TopUpRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : TopUpRequestStatus,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'amount' : IDL.Nat,
    'utrRef' : IDL.Text,
  });
  const Banner = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'ctaLink' : IDL.Text,
    'imageUrl' : IDL.Text,
    'ctaText' : IDL.Text,
    'subtitle' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Game = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'currency' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'user' : IDL.Principal,
    'totalDiamonds' : IDL.Nat,
  });
  const DiamondPackage = IDL.Record({
    'id' : IDL.Nat,
    'diamondAmount' : IDL.Nat,
    'name' : IDL.Text,
    'gameId' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const PaymentConfig = IDL.Record({
    'ifscCode' : IDL.Opt(IDL.Text),
    'bankName' : IDL.Opt(IDL.Text),
    'upiId' : IDL.Opt(IDL.Text),
    'accountNumber' : IDL.Opt(IDL.Text),
    'accountHolder' : IDL.Opt(IDL.Text),
  });
  const SiteConfig = IDL.Record({
    'backgroundColor' : IDL.Text,
    'tagline' : IDL.Text,
    'primaryColor' : IDL.Text,
    'banners' : IDL.Vec(Banner),
    'discountPercent' : IDL.Nat,
    'siteName' : IDL.Text,
    'promoText' : IDL.Text,
    'logoUrl' : IDL.Text,
    'featuredSectionHeading' : IDL.Text,
    'footerText' : IDL.Text,
  });
  const UserStats = IDL.Record({
    'totalOrders' : IDL.Nat,
    'usersThisMonth' : IDL.Nat,
    'activeCustomers' : IDL.Nat,
    'pendingOrders' : IDL.Nat,
    'pendingTopUps' : IDL.Nat,
    'completedOrders' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBanner' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'addGame' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addPackage' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'approveTopUpRequest' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createTopUpRequest' : IDL.Func(
        [IDL.Nat, PaymentMethod, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'creditWallet' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'generateRedeemCode' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Text], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllRedeemCodes' : IDL.Func([], [IDL.Vec(RedeemCode)], ['query']),
    'getAllTopUpRequests' : IDL.Func([], [IDL.Vec(TopUpRequest)], ['query']),
    'getBanners' : IDL.Func([], [IDL.Vec(Banner)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getLeaderboard' : IDL.Func([], [IDL.Vec(LeaderboardEntry)], ['query']),
    'getMyTopUpRequests' : IDL.Func([], [IDL.Vec(TopUpRequest)], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getPackages' : IDL.Func([IDL.Nat], [IDL.Vec(DiamondPackage)], ['query']),
    'getPaymentConfig' : IDL.Func([], [IDL.Opt(PaymentConfig)], ['query']),
    'getSiteConfig' : IDL.Func([], [IDL.Opt(SiteConfig)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserStats' : IDL.Func([], [UserStats], ['query']),
    'getWalletBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [IDL.Nat], []),
    'redeemCode' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'rejectTopUpRequest' : IDL.Func([IDL.Nat], [], []),
    'removeBanner' : IDL.Func([IDL.Nat], [], []),
    'removeGame' : IDL.Func([IDL.Nat], [], []),
    'removePackage' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setPaymentConfig' : IDL.Func([PaymentConfig], [], []),
    'setSiteConfig' : IDL.Func([SiteConfig], [], []),
    'updateBanner' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateGame' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updatePackage' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };