/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Banner {
  'id' : bigint,
  'title' : string,
  'ctaLink' : string,
  'imageUrl' : string,
  'ctaText' : string,
  'subtitle' : string,
}
export interface DiamondPackage {
  'id' : bigint,
  'diamondAmount' : bigint,
  'name' : string,
  'gameId' : bigint,
  'price' : bigint,
}
export interface Game {
  'id' : bigint,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'currency' : string,
}
export interface LeaderboardEntry {
  'user' : Principal,
  'totalDiamonds' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'playerId' : string,
  'user' : Principal,
  'gameId' : bigint,
  'timestamp' : Time,
  'packageId' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface PaymentConfig {
  'ifscCode' : [] | [string],
  'bankName' : [] | [string],
  'upiId' : [] | [string],
  'accountNumber' : [] | [string],
  'accountHolder' : [] | [string],
}
export type PaymentMethod = { 'upi' : null } |
  { 'bank' : null };
export interface RedeemCode {
  'redeemedBy' : [] | [Principal],
  'code' : string,
  'redeemed' : boolean,
  'createdAt' : Time,
  'amount' : bigint,
}
export interface SiteConfig {
  'backgroundColor' : string,
  'tagline' : string,
  'primaryColor' : string,
  'banners' : Array<Banner>,
  'discountPercent' : bigint,
  'siteName' : string,
  'promoText' : string,
  'logoUrl' : string,
  'featuredSectionHeading' : string,
  'footerText' : string,
}
export type Time = bigint;
export interface TopUpRequest {
  'id' : bigint,
  'status' : TopUpRequestStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Time,
  'user' : Principal,
  'amount' : bigint,
  'utrRef' : string,
}
export type TopUpRequestStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface UserStats {
  'totalOrders' : bigint,
  'usersThisMonth' : bigint,
  'activeCustomers' : bigint,
  'pendingOrders' : bigint,
  'pendingTopUps' : bigint,
  'completedOrders' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : bigint,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBanner' : ActorMethod<[string, string, string, string, string], bigint>,
  'addGame' : ActorMethod<[string, string, string], bigint>,
  'addPackage' : ActorMethod<[bigint, string, bigint, bigint], bigint>,
  'approveTopUpRequest' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createTopUpRequest' : ActorMethod<[bigint, PaymentMethod, string], bigint>,
  'creditWallet' : ActorMethod<[Principal, bigint], undefined>,
  'generateRedeemCode' : ActorMethod<[bigint, bigint], string>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllRedeemCodes' : ActorMethod<[], Array<RedeemCode>>,
  'getAllTopUpRequests' : ActorMethod<[], Array<TopUpRequest>>,
  'getBanners' : ActorMethod<[], Array<Banner>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGames' : ActorMethod<[], Array<Game>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardEntry>>,
  'getMyTopUpRequests' : ActorMethod<[], Array<TopUpRequest>>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getPackages' : ActorMethod<[bigint], Array<DiamondPackage>>,
  'getPaymentConfig' : ActorMethod<[], [] | [PaymentConfig]>,
  'getSiteConfig' : ActorMethod<[], [] | [SiteConfig]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserStats' : ActorMethod<[], UserStats>,
  'getWalletBalance' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, bigint, bigint], bigint>,
  'redeemCode' : ActorMethod<[string], bigint>,
  'rejectTopUpRequest' : ActorMethod<[bigint], undefined>,
  'removeBanner' : ActorMethod<[bigint], undefined>,
  'removeGame' : ActorMethod<[bigint], undefined>,
  'removePackage' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setPaymentConfig' : ActorMethod<[PaymentConfig], undefined>,
  'setSiteConfig' : ActorMethod<[SiteConfig], undefined>,
  'updateBanner' : ActorMethod<
    [bigint, string, string, string, string, string],
    undefined
  >,
  'updateGame' : ActorMethod<
    [bigint, string, string, string, boolean],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updatePackage' : ActorMethod<[bigint, string, bigint, bigint], undefined>,
  'upgradeToAdmin' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];