/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface LeaderboardEntry {
    user: Principal;
    totalDiamonds: bigint;
}
export type Time = bigint;
export interface Game {
    id: bigint;
    name: string;
    description: string;
}
export interface TopUpRequest {
    id: bigint;
    status: TopUpRequestStatus;
    paymentMethod: PaymentMethod;
    createdAt: Time;
    user: Principal;
    amount: bigint;
    utrRef: string;
}
export interface DiamondPackage {
    id: bigint;
    diamondAmount: bigint;
    name: string;
    gameId: bigint;
    price: bigint;
}
export interface RedeemCode {
    redeemedBy?: Principal;
    code: string;
    redeemed: boolean;
    createdAt: Time;
    amount: bigint;
}
export interface Order {
    id: bigint;
    status: OrderStatus;
    playerId: string;
    user: Principal;
    gameId: bigint;
    timestamp: Time;
    packageId: bigint;
}
export interface UserProfile {
    name: string;
    email?: string;
}
export interface PaymentConfig {
    ifscCode?: string;
    bankName?: string;
    upiId?: string;
    accountNumber?: string;
    accountHolder?: string;
}
export enum OrderStatus {
    pending = "pending",
    completed = "completed",
    failed = "failed"
}
export enum PaymentMethod {
    upi = "upi",
    bank = "bank"
}
export enum TopUpRequestStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addPackage(gameId: bigint, name: string, diamondAmount: bigint, price: bigint): Promise<bigint>;
    approveTopUpRequest(requestId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createTopUpRequest(amount: bigint, paymentMethod: PaymentMethod, utrRef: string): Promise<bigint>;
    creditWallet(user: Principal, amount: bigint): Promise<void>;
    generateRedeemCode(amount: bigint, codeLength: bigint): Promise<string>;
    getAllOrders(): Promise<Array<Order>>;
    getAllRedeemCodes(): Promise<Array<RedeemCode>>;
    getAllTopUpRequests(): Promise<Array<TopUpRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGames(): Promise<Array<Game>>;
    getLeaderboard(): Promise<Array<LeaderboardEntry>>;
    getMyTopUpRequests(): Promise<Array<TopUpRequest>>;
    getOrders(): Promise<Array<Order>>;
    getPackages(gameId: bigint): Promise<Array<DiamondPackage>>;
    getPaymentConfig(): Promise<PaymentConfig | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWalletBalance(): Promise<bigint>;
    isCallerAdmin(): Promise<boolean>;
    placeOrder(playerId: string, gameId: bigint, packageId: bigint): Promise<bigint>;
    redeemCode(code: string): Promise<bigint>;
    rejectTopUpRequest(requestId: bigint): Promise<void>;
    removePackage(packageId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setPaymentConfig(newConfig: PaymentConfig): Promise<void>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<void>;
    updatePackage(packageId: bigint, name: string, diamondAmount: bigint, price: bigint): Promise<void>;
}
import type { Order as _Order, OrderStatus as _OrderStatus, PaymentConfig as _PaymentConfig, PaymentMethod as _PaymentMethod, RedeemCode as _RedeemCode, Time as _Time, TopUpRequest as _TopUpRequest, TopUpRequestStatus as _TopUpRequestStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addPackage(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addPackage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addPackage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async approveTopUpRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.approveTopUpRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveTopUpRequest(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createTopUpRequest(arg0: bigint, arg1: PaymentMethod, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createTopUpRequest(arg0, to_candid_PaymentMethod_n3(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTopUpRequest(arg0, to_candid_PaymentMethod_n3(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async creditWallet(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.creditWallet(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.creditWallet(arg0, arg1);
            return result;
        }
    }
    async generateRedeemCode(arg0: bigint, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.generateRedeemCode(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.generateRedeemCode(arg0, arg1);
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRedeemCodes(): Promise<Array<RedeemCode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRedeemCodes();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRedeemCodes();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTopUpRequests(): Promise<Array<TopUpRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTopUpRequests();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTopUpRequests();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGames(): Promise<Array<Game>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGames();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGames();
            return result;
        }
    }
    async getLeaderboard(): Promise<Array<LeaderboardEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeaderboard();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeaderboard();
            return result;
        }
    }
    async getMyTopUpRequests(): Promise<Array<TopUpRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTopUpRequests();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTopUpRequests();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrders();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrders();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPackages(arg0: bigint): Promise<Array<DiamondPackage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPackages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPackages(arg0);
            return result;
        }
    }
    async getPaymentConfig(): Promise<PaymentConfig | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPaymentConfig();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPaymentConfig();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWalletBalance(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getWalletBalance();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWalletBalance();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(arg0: string, arg1: bigint, arg2: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, arg2);
            return result;
        }
    }
    async redeemCode(arg0: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.redeemCode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.redeemCode(arg0);
            return result;
        }
    }
    async rejectTopUpRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectTopUpRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectTopUpRequest(arg0);
            return result;
        }
    }
    async removePackage(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removePackage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removePackage(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n30(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setPaymentConfig(arg0: PaymentConfig): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setPaymentConfig(to_candid_PaymentConfig_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setPaymentConfig(to_candid_PaymentConfig_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n34(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n34(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePackage(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePackage(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePackage(arg0, arg1, arg2, arg3);
            return result;
        }
    }
}
function from_candid_OrderStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentConfig_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentConfig): PaymentConfig {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_RedeemCode_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RedeemCode): RedeemCode {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_TopUpRequestStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopUpRequestStatus): TopUpRequestStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_TopUpRequest_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TopUpRequest): TopUpRequest {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PaymentConfig]): PaymentConfig | null {
    return value.length === 0 ? null : from_candid_PaymentConfig_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    redeemedBy: [] | [Principal];
    code: string;
    redeemed: boolean;
    createdAt: _Time;
    amount: bigint;
}): {
    redeemedBy?: Principal;
    code: string;
    redeemed: boolean;
    createdAt: Time;
    amount: bigint;
} {
    return {
        redeemedBy: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.redeemedBy)),
        code: value.code,
        redeemed: value.redeemed,
        createdAt: value.createdAt,
        amount: value.amount
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TopUpRequestStatus;
    paymentMethod: _PaymentMethod;
    createdAt: _Time;
    user: Principal;
    amount: bigint;
    utrRef: string;
}): {
    id: bigint;
    status: TopUpRequestStatus;
    paymentMethod: PaymentMethod;
    createdAt: Time;
    user: Principal;
    amount: bigint;
    utrRef: string;
} {
    return {
        id: value.id,
        status: from_candid_TopUpRequestStatus_n17(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n19(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        user: value.user,
        amount: value.amount,
        utrRef: value.utrRef
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ifscCode: [] | [string];
    bankName: [] | [string];
    upiId: [] | [string];
    accountNumber: [] | [string];
    accountHolder: [] | [string];
}): {
    ifscCode?: string;
    bankName?: string;
    upiId?: string;
    accountNumber?: string;
    accountHolder?: string;
} {
    return {
        ifscCode: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.ifscCode)),
        bankName: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.bankName)),
        upiId: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.upiId)),
        accountNumber: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.accountNumber)),
        accountHolder: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.accountHolder))
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    playerId: string;
    user: Principal;
    gameId: bigint;
    timestamp: _Time;
    packageId: bigint;
}): {
    id: bigint;
    status: OrderStatus;
    playerId: string;
    user: Principal;
    gameId: bigint;
    timestamp: Time;
    packageId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n8(_uploadFile, _downloadFile, value.status),
        playerId: value.playerId,
        user: value.user,
        gameId: value.gameId,
        timestamp: value.timestamp,
        packageId: value.packageId
    };
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): TopUpRequestStatus {
    return "pending" in value ? TopUpRequestStatus.pending : "approved" in value ? TopUpRequestStatus.approved : "rejected" in value ? TopUpRequestStatus.rejected : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    bank: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "bank" in value ? PaymentMethod.bank : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "completed" in value ? OrderStatus.completed : "failed" in value ? OrderStatus.failed : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RedeemCode>): Array<RedeemCode> {
    return value.map((x)=>from_candid_RedeemCode_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TopUpRequest>): Array<TopUpRequest> {
    return value.map((x)=>from_candid_TopUpRequest_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n6(_uploadFile, _downloadFile, x));
}
function to_candid_OrderStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentConfig_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentConfig): _PaymentConfig {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ifscCode?: string;
    bankName?: string;
    upiId?: string;
    accountNumber?: string;
    accountHolder?: string;
}): {
    ifscCode: [] | [string];
    bankName: [] | [string];
    upiId: [] | [string];
    accountNumber: [] | [string];
    accountHolder: [] | [string];
} {
    return {
        ifscCode: value.ifscCode ? candid_some(value.ifscCode) : candid_none(),
        bankName: value.bankName ? candid_some(value.bankName) : candid_none(),
        upiId: value.upiId ? candid_some(value.upiId) : candid_none(),
        accountNumber: value.accountNumber ? candid_some(value.accountNumber) : candid_none(),
        accountHolder: value.accountHolder ? candid_some(value.accountHolder) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    completed: null;
} | {
    failed: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.completed ? {
        completed: null
    } : value == OrderStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    bank: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.bank ? {
        bank: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
